baseURL: 'https://mon.1o0.jp/'
languageCode: "ja"
defaultContentLanguage: "ja"
hasCJKLanguage: true
title: '問学研究会'
theme:  ["github.com/Mitrichius/hugo-theme-anubis"]

menu:
  main:
  - identifier: bookclub
    name: '読書倶楽部'
    title: '読書倶楽部'
    url: /bookclub/
    weight: 0

params:
  social:
  - id: github
    name: mon2org

module:
  imports:
   - path: github.com/mon2org/bookclub
     mounts:
     - source: .
       target: content/bookclub

markup:
  goldmark:
    renderer:
      unsafe: true 